name: hyper-task-manager

services:
  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network

  hyper-service:
    container_name: hyper-task-manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - hyper-task-manager-network
    depends_on:
      - mongodb

volumes:
  mongo-data:

networks:
  hyper-task-manager-network: