name: task-manager-app

services:
  mongodb:
    image: mongo:6.0.8
    container_name: task-manager-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - task-manager-data:/data/db
    networks:
      - task-manager-network

  task-manager-app:
    container_name: task-manager-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - task-manager-network
    depends_on:
      - mongodb

volumes:
  task-manager-data:

networks:
  task-manager-network: